/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Mobile iphone = new Iphone("iphone x7", "white", "brand");
        Person person = new Person("zhulii", iphone);
        person.makeCall("hello world!");
        Mobile andoird = new Andriod("andriod x7", "white", "brand");

        person.setMobile(andoird);
        person.makeCall("hello!");
    }
}
